guestbook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from .views import index, message_post, message_table 
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^add_message', message_post, name='add_message'),
    re_path(r'^result_table/$', message_table, name='result_table'),
]

app_name='guestbook'

lab_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

app_name='lab_1'

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

my_experience/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from .views import my_experience
#url for app
urlpatterns = [
    re_path(r'^my_resume/$', my_experience, name='my_resume'),
]

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from .views import portfolio

urlpatterns = [
    re_path(r'^portfolio/$', portfolio, name='portfolio'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1
from guestbook.views import message_post as message_post
from my_experience.views import my_experience as exp
from portfolio.views import portfolio as port

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^$', index_lab1, name='index'),
    re_path(r'^guestbook/', include('guestbook.urls')),
    re_path(r'^my_resume/$', exp, name='my_resume'),
    re_path(r'^portfolio/$', port, name='portfolio'),
]

guestbook/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return self.message

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

my_experience/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models

# Create your models here.

guestbook/forms.py
from django import forms

class Message_Form(forms.Form):
    
    error_messages = {
        'required': 'Diisi dong uwu',
        'invalid': 'Isi pake email plz',
    }

    attrs = {
        'class': 'form-control'
    }
    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

guestbook/views.py
from django.shortcuts import render
from datetime import datetime, date
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message

# Create your views here.
response = {}

def index(request):
    response['message_form'] = Message_Form
    return render(request, 'guestbook.html', response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'], message=response['message'])
        message.save()
        html ='form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/')
    
def message_table(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'table.html'
    return render(request, html , response)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from django.http import HttpResponseRedirect
# Enter your name here
mhs_name = 'Muhammad Archie Antareza' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2001,1,23) #TODO Implement this, format (Year, Month, Date)
npm = '03411840000007' # TODO Implement this
ttl = 'Cirebon, 23 January 2001'
asal = 'Surabaya'
kuliah='Geophysical Engineering (Undergraduate)'
univ ='Institut Teknologi Sepuluh Nopember (ITS)'
ans = 'Archie is a Geophysical Engineering student with insatiable thirst for knowledge and new experiences. First introduced to the world of programming through a lecture using MATLAB, he has since developed an interest in computer science and data science. Realizing the imminent rapid technological advancements of Industrial Revolution 4.0, he strives to promote the collaboration of data science and geophysics.'
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm, 'ttl': ttl, 'asal': asal, 'kuliah': kuliah, 'univ': univ, 'ans': ans}
    return render(request, 'index_lab1.html', response)
    
def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

my_experience/views.py
from django.shortcuts import render

mhs_name = 'Muhammad Archie Antareza'
pengalaman_1 = 'Professionalism division staff of Society of Exploration Geophysicists (SEG) ITS SC'
pengalaman1_desc = 'In charge of holding knowledge upgrading events (Short Courses, Seminars, Guest Lectures, Workshops, and Open Discussions) regarding exploration geophysics. Have successfully held one Short Course so far. Working with a team of 7 people.'
pengalaman_2 = 'Liason Officer of Geoscience Atmosphere (Geosphere) 2019, Surabaya'
pengalaman2_desc = 'Accepted as a part of the Liason Officer (LO) team for Geosphere 2019, a geoscience big event held by Himpunan Mahasiswa Teknik Geofisika ITS (HMTG ITS). The LO team actively receives skill upgrading before working on the D-day. Working with a team of 31 people.'
# Create your views here.
def my_experience(request):
    response = {'name': mhs_name,'peng1': pengalaman_1, 'peng2': pengalaman_2, 'desc1': pengalaman1_desc, 'desc2': pengalaman2_desc}
    return render(request, 'my_experience.html', response)

portfolio/views.py
from django.shortcuts import render

desc1='This website is actually my first project.'
# Create your views here.
def portfolio(request):
    response = {'desc1': desc1}
    return render(request, 'portfolio.html', response)

guestbook/templates/form_result.html
{% extends "layout/base.html" %}
{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}

<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-
{{name}}
    by {{ email }}
</textarea>
{% endblock %}
{% block footer %}
    <p> &copy; {{name}} </p>
{% endblock %}

guestbook/templates/guestbook.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <link href="{% static 'profil.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <meta charset="UTF-8">
        <title>Guestbook</title>    
	</head>
	<body>
        <div style="background-image: url(https://www.everynation.org/wp-content/uploads/2018/02/Monthly-Website-Header-background.jpg)">
			<h1> <img src="http://icons.iconarchive.com/icons/enhancedlabs/lha-objects/128/Globe-icon.png"> Message Corner!</h1>
		</div>
        <nav id="nav">
            <ul>
            <li><a href="https://myafirst-app.herokuapp.com/">Profile</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/my_resume/">Resume</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/portfolio/">Portfolio</a></li>
            </ul>
        </nav>
        <section name="form">
            {% block form %}
            <h2>Send Message</h2>
            <form id="form" method="POST" action="{% url 'guestbook:add_message' %}">
                {% csrf_token %}
                {{ message_form }}
                <br>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </section>
        {% endblock %}
	</body>
</html>

guestbook/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <link href="{% static 'profil.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <meta charset="UTF-8">
        <title>{{ name }}'s Homepage</title>    
	</head>
	<body>
        <div style="background-image: url(https://www.everynation.org/wp-content/uploads/2018/02/Monthly-Website-Header-background.jpg)">
			<h1> <img src="http://icons.iconarchive.com/icons/enhancedlabs/lha-objects/128/Globe-icon.png"> Welcome to my Profile!</h1>
		</div>
        <nav id="nav">
            <ul>
            <li><a href="https://myafirst-app.herokuapp.com/">Profile</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/my_resume/">Resume</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/portfolio/">Portfolio</a></li>
            </ul>
        </nav>
        <section name="form">
            <h2>Send Message</h2>
            <form id="form" method="POST" action="{% url 'guestbook:message_post' %}">
                {% csrf_token %}
                {{ message_form }}
                <br>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </section>
        {% block content %}
        {% endblock %}
	</body>
</html>

guestbook/templates/partials/footer.html
<html lang="en">
	<head>
        <link href="{% static 'profil.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <meta charset="UTF-8">   
	</head>
    <footer>
        &copy; Copyright 2019 HTML.am
    </footer>
</html>

guestbook/templates/partials/header.html
<html lang="en">
	<head>
        <link href="{% static 'profil.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <meta charset="UTF-8">    
	</head>
	<body>
        <div style="background-image: url(https://www.everynation.org/wp-content/uploads/2018/02/Monthly-Website-Header-background.jpg)">
			<h1> <img src="http://icons.iconarchive.com/icons/enhancedlabs/lha-objects/128/Globe-icon.png"> Message Corner!</h1>
		</div>
        <nav id="nav">
            <ul>
            <li><a href="https://myafirst-app.herokuapp.com/">Profile</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/my_resume/">Resume</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/portfolio/">Portfolio</a></li>
            </ul>
        </nav>
    </body>
</html>

guestbook/templates/table.html
{% extends "layout/base.html" %}
{% block title %} Kumpulan Pesan {% endblock %}
{% block content %}
<!-- Populate semua isi pesan dari model -->
<table class="table">
    <thead>
        <th>Nama</th>
        <th>Email</th>
        <th>Pesan</th>
        <th>Dibuat Pada</th>
    </thead>
    <tbody>
<!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
        <style> 
            tr.warning {
                background-color: red
            }
            
            tr.success {
                background-color: greenyellow
            }
        </style>
        {% for i in message %}
        {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
        <tr class="warning"> {% else %} <tr class="success">
            {% endif %}
            <td> {{i.name}} </td>
            <td> {{i.email}} </td>
            <td> {{i.message}} </td>
            <td> {{i.created_date.time}} </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

lab_1/templates/index_lab1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <link href="{% static 'profil.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <meta charset="UTF-8">
        <title>{{ name }}'s Homepage</title>    
	</head>
	<body>
        <div style="background-image: url(https://www.everynation.org/wp-content/uploads/2018/02/Monthly-Website-Header-background.jpg)">
			<h1> <img src="http://icons.iconarchive.com/icons/enhancedlabs/lha-objects/128/Globe-icon.png"> Welcome to my Profile!</h1>
		</div>
        <nav id="nav">
            <ul>
            <li><a href="https://myafirst-app.herokuapp.com/">Profile</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/my_resume/">Resume</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/portfolio/">Portfolio</a></li>
            </ul>
        </nav>

        <p class="aligncenter">
            <img src="https://i.ibb.co/xqkbK5q/Archie01.jpg" alt="Archie01">
        </p>
		<div>
			<div id="main">
                <h1>Hello! My name is {{ name }}</h1>
                <article>NPM : {{ npm }}</article>
                <article>I am {{ age }} years old</article>
                <article>Wanna know more about me?</article>
                <br>
                <p> Place, Date of Birth: {{ ttl }} </p>
                <p> Place of Origin: {{ asal }} </p>  
                <p> Current Education: {{ kuliah }} </p>
                <p> Institution: {{ univ }} </p>
			</div>
                <p class="harapan"> About Me: </p>
                <p class="harapanans"> {{ ans }} </p>
		</div>
	</body>
</html>

lab_1/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">My Profile</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">Experiences</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

my_experience/templates/my_experience.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <link href="{% static 'profil.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <meta charset="UTF-8">
        <title>{{ name }}'s Resume</title>    
	</head>
	<body>
        <div style="background-image: url(https://www.everynation.org/wp-content/uploads/2018/02/Monthly-Website-Header-background.jpg)">
			<h1> <img src="http://icons.iconarchive.com/icons/enhancedlabs/lha-objects/128/Globe-icon.png"> Welcome to my Profile!</h1>
		</div>
        <nav id="nav">
            <ul>
            <li><a href="https://myafirst-app.herokuapp.com/">Profile</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/my_resume/">Resume</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/portfolio/">Portfolio</a></li>
            </ul>
        </nav>
		<div>
			<div id="main">
                <h1>Resume</h1>
                <article>My Experiences</article>
                <p class="peng"><img src ="https://avatars0.githubusercontent.com/u/5721267?s=280&v=4"></p>
                <p class="exp"> {{ peng1 }} </p>
                <p class="expdate"> March 2019 - Present </p>
                <article class="expdesc"> {{ desc1 }} </article>
                <br>
                <p class="exp"> {{ peng2 }} </p>
                <p class="expdate"> May 2019 - Present </p>
                <article class="expdesc"> {{ desc2 }} </article>
			</div>
		</div>
	</body>
</html>

portfolio/templates/portfolio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <link href="{% static 'profil.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <meta charset="UTF-8">
        <title>{{ name }}'s Experiences</title>    
	</head>
	<body>
        <div style="background-image: url(https://www.everynation.org/wp-content/uploads/2018/02/Monthly-Website-Header-background.jpg)">
			<h1> <img src="http://icons.iconarchive.com/icons/enhancedlabs/lha-objects/128/Globe-icon.png"> Welcome to my Profile!</h1>
		</div>
        <nav id="nav">
            <ul>
            <li><a href="https://myafirst-app.herokuapp.com/">Profile</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/my_resume/">Resume</a></li>
            <li><a href="https://myafirst-app.herokuapp.com/portfolio/">Portfolio</a></li>
            </ul>
        </nav>
		<div>
			<div id="main">
                <h1>My Portfolio</h1>
                <article> {{ desc1 }} </article>
			</div>
		</div>
	</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">My Profile</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">Experiences</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}